version: '3.9'

services:
  postgres:
    image: postgres:13
    container_name: task_container
    ports:
      - "6666:5432"
    environment:
      POSTGRES_DB: task_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - ./config/postgres-data:/var/lib/postgresql/data
